baseURL = 'http://localhost:1313/'
locale = 'en-US'
title = 'Priyanshu Dongre'
theme = 'void'

[params]
  [params.social]
    github = "https://github.com/PriyanshuAnsh"
    email = "priyanshudongre@gmail.com"
    linkedin = "https://linkedin.com/in/priyanshudongre"
  [params.avatar]
    url = "/images/avatar.webp"

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 40

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6
    ordered = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[build]
  [build.buildStats]
    enable = true
