baseURL = 'http://localhost:1313/'
locale = 'en-US'
defaultContentLanguage = 'en'
title = 'Priyanshu Dongre'
theme = 'reimu'

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions.passthrough]
enable = true
delimiters.block = [["\\[", "\\]"], ["$$", "$$"]]
delimiters.inline = [["\\(", "\\)"], ["$", "$"]]

[markup.tableOfContents]
startLevel = 1
endLevel = 6
ordered = false
